services:
  notes-api:
    image: notes-api:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-api
    ports:
      - "${API_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${API_ENV}
      - Jwt__Key=${JWT_KEY}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    networks:
      - notes-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - notes-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Panel de control de Prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - notes-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Panel de control de Grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - notes-network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

networks:
  notes-network:
    driver: bridge

volumes:
  grafana-storage:
  postgres-data:
