services:
  notes-api:
    image: notes-api:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-api
    ports:
      - "${API_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${API_ENV}
      - Jwt__Key=${JWT_KEY}
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge
