apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api-deployment
  labels:
    app: notes-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-api
  template:
    metadata:
      labels:
        app: notes-api
    spec:
      containers:
      - name: notes-api
        image: notes-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: notes-api-config
        - secretRef:
            name: notes-api-secrets
        livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15 # Espera 15 seg antes de empezar a chequear
            periodSeconds: 20       # Chequea cada 20 seg
        readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5  # Empieza casi de inmediato
            periodSeconds: 10